// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ledgerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger.ledger_entries (
    identifier, transaction_id, account_id, amount, direction, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateLedgerEntryParams struct {
	Identifier    uuid.UUID
	TransactionID int64
	AccountID     int64
	Amount        pgtype.Numeric
	Direction     LedgerEntryDirection
	CreatedAt     time.Time
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.Identifier,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.Direction,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO ledger.transactions (
    identifier, transfer_id, created_at, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id
`

type CreateTransactionParams struct {
	Identifier uuid.UUID
	TransferID int64
	CreatedAt  time.Time
	Status     string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Identifier,
		arg.TransferID,
		arg.CreatedAt,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccountBalanceAndLock = `-- name: GetAccountBalanceAndLock :one
SELECT available_balance, updated_at
FROM ledger.account_balances
WHERE account_id = $1
FOR UPDATE
`

type GetAccountBalanceAndLockRow struct {
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) GetAccountBalanceAndLock(ctx context.Context, accountID int64) (GetAccountBalanceAndLockRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceAndLock, accountID)
	var i GetAccountBalanceAndLockRow
	err := row.Scan(&i.AvailableBalance, &i.UpdatedAt)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE ledger.account_balances
SET available_balance = $2,
    updated_at = $3
WHERE account_id = $1
`

type UpdateAccountBalanceParams struct {
	AccountID        int64
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.AccountID, arg.AvailableBalance, arg.UpdatedAt)
	return err
}
