// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ledgerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger.ledger_entries (identifier, transaction_id, account_id, amount, direction, created_at)
VALUES (
    $1,
    (SELECT transactions.id FROM ledger.transactions where transactions.identifier = $2),
    (SELECT accounts.id FROM identity.accounts where accounts.identifier = $3),
    $4,
    $5,
    $6
)
`

type CreateLedgerEntryParams struct {
	Identifier   uuid.UUID
	Identifier_2 uuid.UUID
	Identifier_3 uuid.UUID
	Amount       pgtype.Numeric
	Direction    LedgerEntryDirection
	CreatedAt    time.Time
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.Identifier,
		arg.Identifier_2,
		arg.Identifier_3,
		arg.Amount,
		arg.Direction,
		arg.CreatedAt,
	)
	return err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO ledger.transactions (identifier, transfer_id, created_at, status) 
VALUES (
    $1,
    (SELECT transfers.id FROM transfer.transfers WHERE transfers.identifier = $2),
    $3,
    $4
)
`

type CreateTransactionParams struct {
	Identifier   uuid.UUID
	Identifier_2 uuid.UUID
	CreatedAt    time.Time
	Status       string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.Identifier,
		arg.Identifier_2,
		arg.CreatedAt,
		arg.Status,
	)
	return err
}

const getAccountBalanceAndLock = `-- name: GetAccountBalanceAndLock :one
SELECT available_balance, updated_at
FROM ledger.account_balances
WHERE account_id = (
    SELECT accounts.id
    FROM identity.accounts
    WHERE accounts.identifier = $1
)
FOR UPDATE
`

type GetAccountBalanceAndLockRow struct {
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) GetAccountBalanceAndLock(ctx context.Context, identifier uuid.UUID) (GetAccountBalanceAndLockRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceAndLock, identifier)
	var i GetAccountBalanceAndLockRow
	err := row.Scan(&i.AvailableBalance, &i.UpdatedAt)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE ledger.account_balances
SET available_balance = $2,
    updated_at = $3
WHERE account_id = (
    SELECT accounts.id
    FROM identity.accounts
    WHERE accounts.identifier = $1
)
`

type UpdateAccountBalanceParams struct {
	Identifier       uuid.UUID
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Identifier, arg.AvailableBalance, arg.UpdatedAt)
	return err
}
