// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package userdb

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (
    identifier,
    first_name,
    last_name
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserParams struct {
	Identifier uuid.UUID
	FirstName  string
	LastName   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Identifier, arg.FirstName, arg.LastName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name
FROM identity.users
WHERE identifier = $1
`

type GetUserRow struct {
	ID        int64
	FirstName string
	LastName  string
}

func (q *Queries) GetUser(ctx context.Context, identifier uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, identifier)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}
