// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO transfer.transfers (
	identifier, transfer_request_id, executed_at
) VALUES (
    $1,
    (SELECT transfer_requests.id FROM transfer.transfer_requests WHERE transfer_requests.identifier = $2),
    $3
)
`

type CreateTransferParams struct {
	Identifier   uuid.UUID
	Identifier_2 uuid.UUID
	ExecutedAt   time.Time
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.Exec(ctx, createTransfer, arg.Identifier, arg.Identifier_2, arg.ExecutedAt)
	return err
}

const createTransferRequest = `-- name: CreateTransferRequest :exec
INSERT INTO transfer.transfer_requests (
	identifier, from_account_id, to_account_id, amount, status, requested_at
) VALUES (
    $1,
    (SELECT accounts.id FROM identity.accounts WHERE accounts.identifier = $2),
    (SELECT accounts.id FROM identity.accounts WHERE accounts.identifier = $3),
    $4,
    $5,
    $6
)
`

type CreateTransferRequestParams struct {
	Identifier   uuid.UUID
	Identifier_2 uuid.UUID
	Identifier_3 uuid.UUID
	Amount       pgtype.Numeric
	Status       string
	RequestedAt  time.Time
}

func (q *Queries) CreateTransferRequest(ctx context.Context, arg CreateTransferRequestParams) error {
	_, err := q.db.Exec(ctx, createTransferRequest,
		arg.Identifier,
		arg.Identifier_2,
		arg.Identifier_3,
		arg.Amount,
		arg.Status,
		arg.RequestedAt,
	)
	return err
}

const getTranserRequestStatus = `-- name: GetTranserRequestStatus :one
SELECT status, failure_reason
FROM transfer.transfer_requests
WHERE identifier = $1
`

type GetTranserRequestStatusRow struct {
	Status        string
	FailureReason pgtype.Text
}

func (q *Queries) GetTranserRequestStatus(ctx context.Context, identifier uuid.UUID) (GetTranserRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, getTranserRequestStatus, identifier)
	var i GetTranserRequestStatusRow
	err := row.Scan(&i.Status, &i.FailureReason)
	return i, err
}

const updateTransferRequestStatus = `-- name: UpdateTransferRequestStatus :exec
UPDATE transfer.transfer_requests
SET status = $2,
    failure_reason = $3
WHERE identifier = $1
`

type UpdateTransferRequestStatusParams struct {
	Identifier    uuid.UUID
	Status        string
	FailureReason pgtype.Text
}

func (q *Queries) UpdateTransferRequestStatus(ctx context.Context, arg UpdateTransferRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferRequestStatus, arg.Identifier, arg.Status, arg.FailureReason)
	return err
}
