// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_queries.sql

package accountdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO identity.accounts (identifier, user_id, created_at, account_type, currency, status)
SELECT  $1, users.id, $3, $4, $5, $6
FROM identity.users
WHERE users.identifier = $2
`

type CreateAccountParams struct {
	Identifier   uuid.UUID
	Identifier_2 uuid.UUID
	CreatedAt    time.Time
	AccountType  string
	Currency     string
	Status       string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.Identifier,
		arg.Identifier_2,
		arg.CreatedAt,
		arg.AccountType,
		arg.Currency,
		arg.Status,
	)
	return err
}

const getAccountsOwnedByUser = `-- name: GetAccountsOwnedByUser :many
SELECT id,
    identifier account_identifier,
    created_at,
    account_type,
    currency,
    status
FROM identity.accounts
WHERE user_id = (
    SELECT id
    FROM identity.users
    WHERE users.identifier = $1
)
`

type GetAccountsOwnedByUserRow struct {
	ID                int64
	AccountIdentifier uuid.UUID
	CreatedAt         time.Time
	AccountType       string
	Currency          string
	Status            string
}

func (q *Queries) GetAccountsOwnedByUser(ctx context.Context, identifier uuid.UUID) ([]GetAccountsOwnedByUserRow, error) {
	rows, err := q.db.Query(ctx, getAccountsOwnedByUser, identifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsOwnedByUserRow
	for rows.Next() {
		var i GetAccountsOwnedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountIdentifier,
			&i.CreatedAt,
			&i.AccountType,
			&i.Currency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
