// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_queries.sql

package accountdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO identity.accounts (
    identifier,
    user_id,
    created_at,
    account_type,
    currency,
    "status"
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateAccountParams struct {
	Identifier  uuid.UUID
	UserID      int64
	CreatedAt   time.Time
	AccountType string
	Currency    string
	Status      string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Identifier,
		arg.UserID,
		arg.CreatedAt,
		arg.AccountType,
		arg.Currency,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccountsOwnedByUser = `-- name: GetAccountsOwnedByUser :many
SELECT id, identifier, created_at, account_type, currency, status
FROM identity.accounts
WHERE user_id = $1
`

type GetAccountsOwnedByUserRow struct {
	ID          int64
	Identifier  uuid.UUID
	CreatedAt   time.Time
	AccountType string
	Currency    string
	Status      string
}

func (q *Queries) GetAccountsOwnedByUser(ctx context.Context, userID int64) ([]GetAccountsOwnedByUserRow, error) {
	rows, err := q.db.Query(ctx, getAccountsOwnedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsOwnedByUserRow
	for rows.Next() {
		var i GetAccountsOwnedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.CreatedAt,
			&i.AccountType,
			&i.Currency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
