// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accountdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerEntryDirection string

const (
	LedgerEntryDirectionCREDIT LedgerEntryDirection = "CREDIT"
	LedgerEntryDirectionDEBIT  LedgerEntryDirection = "DEBIT"
)

func (e *LedgerEntryDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntryDirection(s)
	case string:
		*e = LedgerEntryDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntryDirection: %T", src)
	}
	return nil
}

type NullLedgerEntryDirection struct {
	LedgerEntryDirection LedgerEntryDirection
	Valid                bool // Valid is true if LedgerEntryDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntryDirection) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntryDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntryDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntryDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntryDirection), nil
}

type IdentityAccount struct {
	ID          int64
	Identifier  uuid.UUID
	UserID      int64
	CreatedAt   time.Time
	AccountType string
	Currency    string
	Status      string
}

type IdentityUser struct {
	ID         int64
	Identifier uuid.UUID
	FirstName  string
	LastName   string
}

type LedgerAccountBalance struct {
	AccountID        int64
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

type LedgerLedgerEntry struct {
	ID            int64
	Identifier    uuid.UUID
	TransactionID int64
	AccountID     int64
	Amount        pgtype.Numeric
	Direction     LedgerEntryDirection
	CreatedAt     time.Time
}

type LedgerTransaction struct {
	ID         int64
	Identifier uuid.UUID
	TransferID int64
	CreatedAt  time.Time
	Status     string
}

type TransferTransfer struct {
	ID            int64
	Identifier    uuid.UUID
	FromAccountID int64
	ToAccountID   int64
	Amount        pgtype.Numeric
	Status        string
	FailureReason pgtype.Text
	CreatedAt     time.Time
}
