// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_balance_queries.sql

package accountbalance

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountBalance = `-- name: CreateAccountBalance :exec
INSERT INTO ledger.account_balances (
    account_id, available_balance, updated_at
) VALUES (
    (SELECT accounts.id FROM identity.accounts WHERE accounts.identifier = $1),
    $2,
    $3
)
`

type CreateAccountBalanceParams struct {
	Identifier       uuid.UUID
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) CreateAccountBalance(ctx context.Context, arg CreateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, createAccountBalance, arg.Identifier, arg.AvailableBalance, arg.UpdatedAt)
	return err
}

const getAccountBalanceAndLock = `-- name: GetAccountBalanceAndLock :one
SELECT available_balance, updated_at
FROM ledger.account_balances
WHERE account_id = (
    SELECT accounts.id
    FROM identity.accounts
    WHERE accounts.identifier = $1
)
FOR UPDATE
`

type GetAccountBalanceAndLockRow struct {
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) GetAccountBalanceAndLock(ctx context.Context, identifier uuid.UUID) (GetAccountBalanceAndLockRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceAndLock, identifier)
	var i GetAccountBalanceAndLockRow
	err := row.Scan(&i.AvailableBalance, &i.UpdatedAt)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE ledger.account_balances
SET available_balance = $2,
    updated_at = $3
WHERE account_id = (
    SELECT accounts.id
    FROM identity.accounts
    WHERE accounts.identifier = $1
)
`

type UpdateAccountBalanceParams struct {
	Identifier       uuid.UUID
	AvailableBalance pgtype.Numeric
	UpdatedAt        time.Time
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Identifier, arg.AvailableBalance, arg.UpdatedAt)
	return err
}
